### PR TITLE
Localisition files are now built in build folder

### PR DESCRIPTION
**Pull request by Spagy**
Moved localisation build files from Source directory to build
directory. This means that git will ignore the files.

### CODE REVIEW

**Comment by KoKuToru** [comment]
`src/i18n/CMakeLists.txt` uses these files.
I am not even sure if we should do this magic in the CMakeLists...
Mabye a simple  `generate-translation.sh` ?

The `CMakeLists.txt` you changed generates the template for translation.
Ssearching `_()` in source and extract translatable from the glade-files

The `src/i18n/CMakeLists.txt` merges the template with the english-translation 
and then merge the english translation to all other translations.

So when a translation misses something, the english-translation will be displayed.

**Comment by Spagy** [comment]
It might be nice to separate the "magic" into a separate file. CMake is nice because it is cross platform.  generate-translation.sh doesn't sound very cross platform.

**Comment by Spagy** [comment]
BTW, why are the strings to be translated placeholders rather than English?

"String literals should be typed in the source code in English, but surrounded by a macro."
from https://developer.gnome.org/gtkmm-tutorial/stable/chapter-internationalization.html.en

**Comment by KoKuToru** [comment]
Because I don't like long texts in my source and I didn't want to use own custom solution for key/value translation.

So we went the gettext route.. to get the extraction-features, but still use keys.

This way the source is free of "translation"

**Comment by Spagy** [comment]
That makes sense but it's difficult to "translate" a key if there is no string to translate. The translator has to guess what the string should be from the context of the code. This isn't good, especially if someone who can't code wants to contribute translations.

So, I think it would be good if either the English .po file is kept up to date (any new keys added to code have translations added in same pull request) or a comment is added next to the code containing the key that says what the string should be.

The second option seems to defeat the point of using keys because text would be in the source in the form of comments. This option could be used as a half way stage so the comment is deleted once the string has been added to the .po file.

**Comment by KoKuToru** [comment]
Of course english should be kept up to date.
I just didn't do it for the latest changes...

Well it's a little different now then it used to be,
ui-text is hardly in source now, because everything is Gtk::Builder now.
Of course we could write everything in english in the ui-files...

But what are you doing when you change the english text ? 
How are you updating the other translations.. ? I have no idea.

I never used gettext before this.

For the exception error codes and error messages for dialogs,
I really don't want to see these messages in source...

**Comment by Spagy** [comment]
Please ignore this in favour of #145

**Pull request closed without merging**
