### PR TITLE
Re written translation buliding and modification to translation initialisation code

### PR DESCRIPTION
**Pull request by Spagy**
If this looks good but needs modifications I'll make them tomorrow. Well, later today technically.

Ok, I've unmessed this up and closed #143.

### CODE REVIEW

**Comment by Spagy** [comment]
toxmm-rewrite builds but produces "Fatal Error Couldn't find translation files" and exits because it looks for translation files in `./Locale`.

If gTox is installed separately and properly (e.g. form AUR), toxmm-rewrite will use those translation files, from `/usr/share/locale/`, and not produce the error.

This pull request fixes that; gTox will look in `./i18n`.

Also, should toxmm-rewrite  bugs be reported to the normal issue tracker?

**Comment by KoKuToru** [comment]
Yeah toxmm-rewrite bugs should be reported in normal issue tracker.. I can add a milestone for `toxmm-rewrite` or a label

**Comment by Spagy** [comment]
Is this okay to merge or are there problems?

**Comment by KoKuToru** [comment]
I will check it when I am at home
Am 14.07.2015 16:52 schrieb "Spagy" <notifications@github.com>:

Is this okay to merge or are there problems?

—
Reply to this email directly or view it on GitHub
<https://github.com/KoKuToru/gTox/pull/145#issuecomment-121267326>.

**Comment by Spagy** [comment]
Thanks (sorry if I sounded impatient)

**Pull request merged**
