### PR TITLE
Fix writing error

### PR DESCRIPTION
**Pull request by Twyz**
Fix writing error in the english translation

### CODE REVIEW

**Comment by KoKuToru** [comment]
updating a `msgid` is not that easy..
you will need to update all references that uses this `msgid` (`gstreamer.cpp`  in this case and all `*.po` files)

This is really why I don't like `gettext`, updating a `msgid` is so much work (or I don't know the tricks)

**Comment by Twyz** [comment]
Oh, i didn't know sorry

**Comment by Spagy** [comment]
This is a "feature" of gettext. The idea is that if the English translation changes even just a little bit then the translators should retranslate or at least check the current translation.

This is because small changes may carry different connotations or make the translation different in a way that a non-speaker of the foreign language may not be able to see. 

I don't know what the deal is with spelling corrections like this. I can't see how this change would need an update in any other language because it makes no change to what translators were translating, assuming they made this correction in their heads as they were translating.

**Comment by KoKuToru** [comment]
@Twyz I took your commits, combined and completed them in PR #207

**Pull request closed without merging**
